- name: variables in ansible
  hosts: local
  connection: local
  vars:
    course: devops with Aws
    trainer: sivakumarreddy
    batch: 84s
  tasks:
    - name: printing course info
      ansible.builtin.debug:
        msg: "i am learning: {{course}} by {{  trainer}} in {{batch}}"


- name: 2nd play
  hosts: local
  vars:
    course: frontend
  tasks:
    vars:
      trainer: sivakumar
    ansible.builtin.debug:
     msg: "printing{{course}} and{{trainer}}"
