- name: local and global vars in ansible
  hosts: local
  vars:
    course: devops with Aws
    trainer: lella 
    batch: 84s
  tasks:
    - name: printing course info
      vars:
        course: ansible
      anible.builtin.debug:
        msg: "learning {{course}} from {{trainer}} in {{batch}}"
  tasks:
    - name: printing couse info again
      ansible.builtin.debug:
        msg: "learning {{course}} from {{trainer}} in {{batch}}"