- name: local and global vars in ansible
  hosts: local
  become: yes
  vars:
    course: devops with Aws
    trainer: lella 
    batch: 84s
  tasks:
    - name: printing course info
      vars:
        course: ansible
      ansible.builtin.debug:
        msg: "learning {{course}} from {{trainer}} in {{batch}}"
  
    - name: printing couse info again
      ansible.builtin.debug:
        msg: "learning {{course}} from {{trainer}} in {{batch}}"

- name: play level variables
  hosts: local
  connection: local
  vars:
    COURSE: DevOps with AWS
    DURATION: 10HR
    TRAINER: Sivakumar
  tasks:
  - name: print course information
    vars:
      COURSE: Ansible
    ansible.builtin.debug:
    #vars refernce should be surrounded by ""
      msg: "Hello {{ COURSE }}, Course Duration: {{ DURATION }}, Trainer is {{ TRAINER }}"

  - name: print course information again
    ansible.builtin.debug:
    #vars refernce should be surrounded by ""
      msg: "Hello {{ COURSE }}, Course Duration: {{ DURATION }}, Trainer is {{ TRAINER }}"