- name: variable preferences
  hosts: local
  connection: local
  vars:
    greeting: "from vars"
  vars_file:
  - course.yaml
  vars_prompt:
  - name: greeting
    prompt: enter greeting
    private: true
  tasks:
  - name: checking varibales 
    vars:
      greeting: from task
  ansabile.builtin.debug:
    msg: "{{ greeting }}"

