- name: conditions
  hosts: local
  connection: local
  vars_propt:
  - name: number
    prompt: "enter a number"
    private: true
  tasks:
    - name: printing numbers
      ansible.builtin.debug:
       msg: "{{number}}is less than 20 "
      when: number < 20