- name: loops for installing
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: installing multiple services
    ansible.builtin.package:
      name: "{{ item }}"
      state: installed
    loop:
    - nginx
    - mysql
    - zip

