- name: loops with both name and state 
  hosts: frontend
 
  tasks:
  - name: installing packages
    ansible.builtin.package:
     name: "{{ item.name }}"
     state: "{{ item.state }}"
    loop:
    - {name: 'nginx', state: 'present'}
    - {name: 'mysql',state: 'absent'}
    - {name: 'zip', state: 'present'}