- name: function or filters in ansible
  hosts: local
  connection: local
  vars:
    names: "rakesh,harsha,shashi,mahi"
  tasks:
  - name: checking default
    ansible.builtin.debug:
      msg: "{{ names | default('ramana') }}"

  - name: spliting names
    ansible.builtin.debug:
      msg: "{{ names | split(',') }}"

  - name: convert list to map
    vars:
      skills:
        - { 'key': 'ramana', 'value': 'java' }
        - { 'key': 'rakesh', 'value':'cpp'}
    ansible.builtin.debug:
      msg: "{{ skills | items2dict }}"

  - name: convert map to list 
    vars:
      name: ramana
      skill: java
      age: "24"
    ansible.builtin.debug:
      msg: "{{ skills | dict2items }}"
    
  - name: uppercase
    vars: 
      name: ramana
    ansible.builtin.debug:
      msg: "{{ names | upper }}"

  - name: lowercaser to upper
    vars: 
      name: RAMANA
    ansible.builtin.debug:
      msg: "{{ name | lower }}"  