- name: shell vs command
  hosts: local
  connection: local
  tasks:
  - name: example for command 
  #in command we can just use the command we cant able to redirect as ls -ltr| /tmp/output.txt for that we hve to use shell
    ansible.builtin.command: "ls -ltr"
    register: output
  
  - name: printing output
    ansible.builtin.debug:
      msg: "{{ output }}" 

  
  - name: shell 
    ansible.builtin.shell: "ls -ltr > /tmp/output.txt"
    register: shell_output
    
 
  - name: printing shell output
    ansible.builtin.debug:
      msg: "{{ shell_output }}"
