- name: playbook1
  hosts: local
  connection: local
  task:
  - name: print hello world
    ansible.builtin.debug:
      msg: "hello world"


- name: playbook2
  hosts: frontend
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: preset