- name: vars promt
  hosts: local
  connection: local
  vars_prompt:
    - name: trainer
      prompt: "enter trainer"
      private: false
  tasks:
  - name: vars promts
    vars:
      course: devops
    ansible.builtin.debug:
      msg: "trainer: {{ trainer }}, course: {{ course }}, "