- name: ansible datatypes
  hosts: local
  connection: local
  vars:
    duration: 100
    uname: "ramana"
    male: true
    course:
    - java
    - springboot
    - shell
    - ansible
    trainers:
      java: "sommana, rohit"
      devops: "sivakumar"
  tasks:
  - name: printing vars
    ansible.builtin.debug:
      msg: "duration: {{ duration }}, name: {{ uname }}, is male?: {{ male }}, courses are:{{ course }} from trainers: {{ trainers }}"