- name: conditions on facts
  hosts: frontend
  become: yes
  tasks: 
  - name: install nginx in ubuntu
    ansibel.builtin.apt:
      name: nginx
      state: present
    when: ansible_os_family=="Debian"
  
  - name: install nginx in red hat
    ansible.builtin.dnf:
      name: nginx
      state: present
    when: ansible_os_family=="RedHat"